### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by techalchemy** [go-macaroon-bakery/py-macaroon-bakery#80]
Per #74 `platform.dist` is removed in python 3.8 which makes this package no longer installable due to the usage of this functionality in `setup.py` as of the last release uploaded to PyPI (`1.2.3`). A new release would be greatly helpful to users trying to consume downstream dependencies of `macaroonbakery` who are also using python 3.8 and who are therefore encountering this issue:

```python
    ERROR: Command errored out with exit status 1:
     command: /home/techalchemy/.virtualenvs/charm-helpers-xyNe4M-M/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0ozktt_y/macaroonbakery/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0ozktt_y/macaroonbakery/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-0ozktt_y/macaroonbakery/pip-egg-info
         cwd: /tmp/pip-install-0ozktt_y/macaroonbakery/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0ozktt_y/macaroonbakery/setup.py", line 42, in <module>
        distribution = platform.dist()
    AttributeError: module 'platform' has no attribute 'dist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by addyess** [comment]
please release new version with updates `setup.py`.  Looks like you just need to cut a new release and push to pypi

**Comment by frankban** [comment]
Version 1.3.0 released.
