### ISSUE TITLE
Protobuf failure since constraint relax in 1.3.3

### ISSUE THREAD

**Issue by gboutry** [go-macaroon-bakery/py-macaroon-bakery#94]
Recently, protobuf constraint was relaxed on macaroon-bakery, going from `>=3.4,<4` to `>=3.4`

Using macaroon-bakery with `protobuf==4.25.1`

It looks like some protobuf files need to be regenerated, which might force to raise the lower limit of `>=3.4` to something greater.

Errors:
```
 INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/_pytest/main.py", line 271, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/_pytest/main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/pluggy/_callers.py", line 152, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/pluggy/_result.py", line 114, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/_pytest/main.py", line 335, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/_pytest/main.py", line 675, in perform_collect
INTERNALERROR>     self.items.extend(self.genitems(node))
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/_pytest/main.py", line 845, in genitems
INTERNALERROR>     yield from self.genitems(subnode)
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/_pytest/main.py", line 842, in genitems
INTERNALERROR>     rep = collect_one_node(node)
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/_pytest/runner.py", line 546, in collect_one_node
INTERNALERROR>     ihook.pytest_collectstart(collector=collector)
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/pluggy/_callers.py", line 113, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/pytest_asyncio/plugin.py", line 612, in pytest_collectstart
INTERNALERROR>     pyobject = collector.obj
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
INTERNALERROR>     self._obj = obj = self._getobj()
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
INTERNALERROR>     return self._importtestmodule()
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
INTERNALERROR>     mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
INTERNALERROR>     importlib.import_module(module_name)
INTERNALERROR>   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
INTERNALERROR>     return _bootstrap._gcd_import(name[level:], package, level)
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
INTERNALERROR>     exec(co, module.__dict__)
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/tests/unit/sunbeam/test_clusterd.py", line 23, in <module>
INTERNALERROR>     from sunbeam.commands.clusterd import (
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/sunbeam/commands/clusterd.py", line 35, in <module>
INTERNALERROR>     from sunbeam.commands.juju import BOOTSTRAP_CONFIG_KEY, JujuStepHelper
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/sunbeam/commands/juju.py", line 38, in <module>
INTERNALERROR>     from sunbeam.jobs.juju import (
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/sunbeam/jobs/juju.py", line 27, in <module>
INTERNALERROR>     from juju.application import Application
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/juju/application.py", line 9, in <module>
INTERNALERROR>     from . import model, tag, utils, jasyncio
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/juju/model.py", line 29, in <module>
INTERNALERROR>     from .client import client, connector
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/juju/client/connector.py", line 7, in <module>
INTERNALERROR>     import macaroonbakery.httpbakery as httpbakery
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/macaroonbakery/httpbakery/__init__.py", line 3, in <module>
INTERNALERROR>     from ._client import (
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/macaroonbakery/httpbakery/_client.py", line 7, in <module>
INTERNALERROR>     import macaroonbakery.bakery as bakery
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/macaroonbakery/bakery/__init__.py", line 75, in <module>
INTERNALERROR>     from ._oven import (
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/macaroonbakery/bakery/_oven.py", line 29, in <module>
INTERNALERROR>     from ._internal import id_pb2
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/macaroonbakery/bakery/_internal/id_pb2.py", line 35, in <module>
INTERNALERROR>     _descriptor.FieldDescriptor(
INTERNALERROR>   File "/home/runner/work/snap-openstack/snap-openstack/sunbeam-python/.tox/py3/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 553, in __new__
INTERNALERROR>     _message.Message._CheckCalledFromGeneratedFile()
INTERNALERROR> TypeError: Descriptors cannot be created directly.
INTERNALERROR> If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
INTERNALERROR> If you cannot immediately regenerate your protos, some other possible workarounds are:
INTERNALERROR>  1. Downgrade the protobuf package to 3.20.x or lower.
INTERNALERROR>  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
INTERNALERROR> 
INTERNALERROR> More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```

**Comment by gboutry** [comment]
Fixed in #95
